- url: https://google.com
  frequency: 3
  regex:
    - name: check_google_exists
      pattern: .*google.*
- url: https://aiven.io
  frequency: 5
- url: https://postman-echo.com/get?client=observer
  frequency: 2
  regex:
    - name: check_observer_exists
      pattern: .*observer
    - name: check_client_exists
      pattern: .*client